In [9]:
#Q1)Use numpy to generate array of 25 random numbers sampled from a standard normal distribution?
import numpy as np
rand_num = np.random.randint(0,25,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)


25 random numbers from a standard normal distribution:
[ 2  3  2 11 13 16  8  8 19  8  2 24 20  3 12 14  0  4  3 13 11 22 13 13
 11]


In [10]:
#Q2)Create a random vector of size 30 and find the mean value.?
np.random.seed(0)
rd = np.random.randint(0,91,30)
rd.mean()

57.166666666666664

In [11]:
#Q3)Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.
matrix10 = np.arange(1,101)
matrix10.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
#Q4)Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(0)
max_min = np.random.rand(10,10)
print(np.max(max_min))
print(np.min(max_min))

0.9883738380592262
0.004695476192547066


In [13]:
#Q5)Find Dot product of two arrays

f = np.array([1,2])

g = np.array([4,5])

h = np.dot(f,g)
h

14

In [14]:
#Q6)Concatenate following arrays along axis=0
x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])


np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
#Q7)How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])


print(np.intersect1d(a, b))


[2 4]


In [16]:
#Q8)Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  7,  8, 10])